[package]
name = "boss_monster_card_reader-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
imageproc = "0.23.0"
thiserror = "1.0.50"

[features]
diag_card_finder = []
